apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: lake-dev
spec:
  selector:
    app: temporal
  ports:
    - port: 7233
      targetPort: 7233
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: lake-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      enableServiceLinks: false
      containers:
        - name: temporal
          image: temporalio/auto-setup:latest
          ports:
            - containerPort: 7233
          env:
            - name: DB
              value: postgres12
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: lakedev
            - name: POSTGRES_PWD
              value: lakedev
            - name: POSTGRES_SEEDS
              value: postgres
            - name: DEFAULT_NAMESPACE_RETENTION
              value: "24h"
          readinessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 15
            periodSeconds: 10
