import { Shield } from 'lucide-react'

export function TermsPage() {
  return (
    <div className="flex-1 overflow-auto">
      <div className="max-w-3xl mx-auto px-6 py-8">
        <div className="flex items-center gap-3 mb-8">
          <div className="p-2 rounded-lg bg-primary/10">
            <Shield className="h-6 w-6 text-primary" />
          </div>
          <div>
            <h1 className="text-2xl font-semibold">Terms of Use</h1>
            <p className="text-sm text-muted-foreground">Last updated: January 29, 2026</p>
          </div>
        </div>

        <div className="space-y-8 text-sm text-foreground/90 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold mb-3">AI-Powered Service</h2>
            <p>
              DoubleZero Data provides an AI-powered assistant that generates and executes database
              queries to answer questions about the DoubleZero network. Responses are generated by
              artificial intelligence and may be inaccurate, incomplete, or outdated. They should not
              be relied upon as authoritative. You are interacting with an AI, not a human.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">AI Provider</h2>
            <p>
              This service uses Anthropic's Claude as its AI provider. Your questions and
              conversation context are sent to Anthropic's API to generate responses. Anthropic's
              own <a href="https://www.anthropic.com/legal/consumer-terms" target="_blank" rel="noopener noreferrer" className="underline hover:text-foreground">terms</a> and <a href="https://www.anthropic.com/legal/privacy" target="_blank" rel="noopener noreferrer" className="underline hover:text-foreground">privacy policy</a> apply
              to that processing.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Data We Collect</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Email and display name</strong> — collected via Google OAuth when you sign in.</li>
              <li><strong>Wallet address</strong> — your Solana public key if you connect a wallet.</li>
              <li><strong>IP address</strong> — used for anonymous usage quota enforcement.</li>
              <li><strong>Questions and conversations</strong> — the queries you submit and the AI responses.</li>
              <li><strong>Usage metrics</strong> — daily question counts and token usage.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">How We Use Your Data</h2>
            <p>
              We use collected data to operate and improve the service, enforce usage quotas, and
              monitor for abuse. We do not sell your data or use it for advertising.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Data Retention</h2>
            <p>
              IP-based usage data is automatically deleted after 90 days. Account information and
              conversation history are retained for as long as your account exists.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Sensitive Information</h2>
            <p>
              Do not submit sensitive personal information, passwords, private keys, or other
              confidential data through this service. Messages may be stored and reviewed to operate
              and improve the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Changes to These Terms</h2>
            <p>
              We may update these terms at any time. Continued use of the service after changes
              constitutes acceptance of the updated terms.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
